-- COLLECTION_MOVIES_SCHEMA.sql
-- Run this script to enable linking movies to collections.

-- 1. Create the Junction Table
CREATE TABLE IF NOT EXISTS public.collection_movies (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  collection_id bigint REFERENCES public.collections(id) ON DELETE CASCADE NOT NULL,
  movie_id bigint REFERENCES public.user_movies(id) ON DELETE CASCADE NOT NULL,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE(collection_id, movie_id) -- Prevent duplicate entries
);

-- 2. Enable RLS
ALTER TABLE public.collection_movies ENABLE ROW LEVEL SECURITY;

-- 3. RLS Policies
-- Since this is a junction table, we check if the user owns the *collection*
-- (assuming only the owner can add/remove movies from their collection)

-- VIEW: User can view if they own the collection
CREATE POLICY "User can view movies in own collection"
ON public.collection_movies FOR SELECT
USING (
  EXISTS (
    SELECT 1 FROM public.collections c
    WHERE c.id = collection_movies.collection_id
    AND c.user_id = auth.uid()
  )
);

-- INSERT: User can insert if they own the collection
CREATE POLICY "User can add movies to own collection"
ON public.collection_movies FOR INSERT
WITH CHECK (
  EXISTS (
    SELECT 1 FROM public.collections c
    WHERE c.id = collection_movies.collection_id
    AND c.user_id = auth.uid()
  )
);

-- DELETE: User can remove movies from own collection
CREATE POLICY "User can remove movies from own collection"
ON public.collection_movies FOR DELETE
USING (
  EXISTS (
    SELECT 1 FROM public.collections c
    WHERE c.id = collection_movies.collection_id
    AND c.user_id = auth.uid()
  )
);

-- 4. Permissions
GRANT USAGE ON SCHEMA public TO authenticated;
GRANT ALL ON TABLE public.collection_movies TO authenticated;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO authenticated;

-- 5. Reload Cache
NOTIFY pgrst, 'reload schema';
