-- 1. Create the table
-- We use 'bigint' for id, and 'uuid' for user_id to link with Supabase Auth
create table public.user_movies (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  title text not null,
  poster_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Enable Row Level Security (RLS)
-- This is crucial so that users can only access their own data
alter table public.user_movies enable row level security;

-- 3. Create Policies

-- Policy: Allow users to view their own movies
create policy "Users can view their own movies"
on public.user_movies for select
using ( auth.uid() = user_id );

-- Policy: Allow users to add their own movies
create policy "Users can insert their own movies"
on public.user_movies for insert
with check ( auth.uid() = user_id );

-- Policy: Allow users to delete their own movies
create policy "Users can delete their own movies"
on public.user_movies for delete
using ( auth.uid() = user_id );

-- Optional: Policy to update (if you plan to allow editing)
create policy "Users can update their own movies"
on public.user_movies for update
using ( auth.uid() = user_id );
