-- 1. Create the table
-- We use 'bigint' for id, and 'uuid' for user_id to link with Supabase Auth
create table if not exists public.user_movies (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  title text not null,
  poster_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Enable Row Level Security (RLS)
-- This is crucial so that users can only access their own data
alter table public.user_movies enable row level security;

-- 3. Create Policies

-- Policy: Allow users to view their own movies
create policy "Users can view their own movies"
on public.user_movies for select
using ( auth.uid() = user_id );

-- Policy: Allow users to add their own movies
create policy "Users can insert their own movies"
on public.user_movies for insert
with check ( auth.uid() = user_id );

-- Policy: Allow users to delete their own movies
create policy "Users can delete their own movies"
on public.user_movies for delete
using ( auth.uid() = user_id );

-- Optional: Policy to update (if you plan to allow editing)
create policy "Users can update their own movies"
on public.user_movies for update
using ( auth.uid() = user_id );

-- -----------------------------------------------------------------------------
-- Collections Table
-- -----------------------------------------------------------------------------

create table if not exists public.collections (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  name text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.collections enable row level security;

create policy "Users can view their own collections"
on public.collections for select
using ( auth.uid() = user_id );

create policy "Users can insert their own collections"
on public.collections for insert
with check ( auth.uid() = user_id );

create policy "Users can delete their own collections"
on public.collections for delete
using ( auth.uid() = user_id );

create policy "Users can update their own collections"
on public.collections for update
using ( auth.uid() = user_id );

-- -----------------------------------------------------------------------------
-- Permissions & Cache Refresh
-- -----------------------------------------------------------------------------
-- Explicitly grant permissions to ensure the table is accessible
GRANT USAGE ON SCHEMA public TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.collections TO anon, authenticated, service_role;

-- Reload the PostgREST schema cache to recognize the new table
NOTIFY pgrst, 'reload schema';
